### ISSUE TITLE
error message when create record audio question.

### ISSUE THREAD

**Issue by StJamesLC** [moodleou/moodle-qbehaviour_selfassess#1]
We are running Moodle 3.5+ (Build: 20180628). I downloaded the plugin for qbehaviour_selfassess v0.7 for Moodle 3.5+ (2020012000). When I create a Record Audio question I get this error: Exception - Call to undefined method question_attempt::get_outer_question_div_unique_id()

**Comment by timhunt** [comment]
I am sorry about that.

That function are are missing was added in Moodle 3.5.6 / 3.6.4 / 3.7 (https://tracker.moodle.org/browse/MDL-65029). So, if your 3.5 install is up-to-date, it will work. 3.5.6 was released 13 May 2019.

I don't think that the Moodle plugins DB lets me set compatibility to that level of detail, so I can't really think what I can do about this.
